name: fooderlich
description: a social recipe app to keep track of new dishes, and share with friends.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.7

  google_fonts: ^2.1.0
  provider: ^5.0.0
  intl: ^0.17.0
  uuid: ^3.0.4
  flutter_colorpicker: ^0.4.0
  cupertino_icons: ^1.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/food_pics/
    - assets/magazine_pics/
    - assets/sample_data/
    - assets/profile_pics/
    - assets/fooderlich_assets/

 